### PR TITLE
Changed speaker for PIMS

### PR DESCRIPTION
**Pull request by ianabc**
Could you switch the speakers with this PR? I've been asked to speak since it's a technical overview of what we're doing.

### CODE REVIEW

**Comment by willingc** [comment]
@ianabc Do you wish to close this PR? It looks as if @fperez has added you to the speaker list :smile:

**Comment by fperez** [comment]
Yes, sorry! I missed the PR notice and fixed it myself separately, I apologize @ianabc. Thanks @willingc for the direct ping... I hadn't realized I'm not subscribed to the entire repo. Taking care of that now :)

I'm closing the PR since it has a conflict and the info is there. Ian, if you'd like me to remove the other two in the team from the listing just let me know, I kept all names since we'd discussed it with everyone...

**Comment by ianabc** [comment]
@fperez That looks great, I just didn't want people to get a nasty surprise if they were expecting a nice talk from Jim and got me instead! As for the content, I'll just be covering where we are and pointing out what we still need to do - it's very much still a work-in progress.

**Comment by fperez** [comment]
perfect, @ianabc, it's meant to be very informal and interactive, no worries.

**Pull request closed without merging**
