### PR TITLE
Adding PDF Notes

### PR DESCRIPTION
**Pull request by rnetro**

### CODE REVIEW

**Comment by willingc** [comment]
@JamiesHQ @minrk Reese has put together some detailed and thoughtful notes from the workshop. I'm going to go ahead and merge these and, if needed, we can iterate on them.

Thanks @rnetro for your help and for a job well done capturing the technical content 🌻 

cc @fperez @ellisonbg

**Comment by rnetro** [comment]
No problem :)
do you want the microsoft word version too so people can edit?

**Comment by willingc** [comment]
@rnetro Sure. Go ahead and submit a pr with the word doc.

**Comment by JamiesHQ** [comment]
This is great @rnetro & @willingc!

@willingc : do Reese's notes incorporate the notes you took? If you would like to send me your notes I can incorporate them into Reese's documents (along with the notes i took). I know @fperez wanted all the notes aggregated into one document _as if_ we had used Hackpad.

**Comment by willingc** [comment]
@JamiesHQ It doesn't entirely cover my notes. Though Reese did capture 90-95% of my notes. I'll do a scan tomorrow. Having internet connectivity problems today as I work in SD.

**Comment by JamiesHQ** [comment]
@willingc : sounds good

**Pull request merged**
