### PR TITLE
Adding slides for PIMS

### PR DESCRIPTION
**Pull request by ianabc**
@fperez: I've added some slides, I rushed a bit so I'll just update them after the fact if they're incomplete.

### CODE REVIEW

**Comment by ianabc** [comment]
the update puts it in LFS (I think...)

**Comment by willingc** [comment]
@ianabc Thanks for the updates. Don't worry about LFS. Is this ready to merge?

**Comment by ianabc** [comment]
@willingc Thanks yes, I think so

**Comment by willingc** [comment]
Okie dokie. I'm going to merge but feel free to open a new pr if you have any changes :-)

**Pull request merged**
